### ISSUE TITLE
Unable to start the app

### ISSUE THREAD

**Issue by mtapdilli** [nrwl/nx-react-native#8] opened 2020-11-12 12:00 UTC
- Running _nx start my-app_ gives below error :
`**The run-ios build requires OSX to run**`

- Running _nx run-android my-app_ gives below error :
`EPERM: operation not permitted, symlink '_**path to the workspace**_\node_modules\react-native' -> '*_path to the workspace*_\apps\my-app\node_modules\react-native'`

- Running _nx build-android my-app_ gives below error :
`spawn _**path to the workspace**_\apps\my-app\android\gradlew ENOENT`

```
Platform : Windows
Nx --version : 10.3.3
```

Steps Followed : 

- Ran npx create-nx-workspace@latest and selected empty workspace layout
And then ran below commands as suggested by @jaysoo in this [comment](https://github.com/nrwl/nx-react-native/issues/1#issuecomment-725812917)
- yarn add @nrwl/react-native@10.4.0-beta.2
nx g @nrwl/react-native:app my-app
....
....

**Comment by nclarx** [comment] 2020-11-12 12:26
Check out the comment about the release on https://github.com/nrwl/nx-react-native/issues/1 that might give you some insight into the constraints. 

If you're on Windows you won't have the simulator for iOS - that's a MacOS only thing as far as I know. Other who know the ecosystem better might have some suggestions?

**Comment by jaysoo** [comment] 2020-11-12 14:09
@nclarx is right, iOS requires a toolchain that only OSX provides. 

For Android, I it looks like the symlink operation didn't work for you -- React Native has hard-coded `node_modules` paths in some of it's scripts so the symlink is needed to work. I'll double-check on a Windows  machine.

**Comment by mtapdilli** [comment] 2020-11-12 18:25
Sure @jaysoo . I was only trying to to Android app did not touch iOS. I rand _nx start my-app_ as it was mentioned that it will "Start JS bundler" and got the error that I have mentioned i.e., **The run-ios build requires OSX to run**

**Comment by jaysoo** [comment] 2020-11-12 18:55
Oh yes, I see there's an erroneous platform check for the bundler builder. I'll patch that.

**Comment by jaysoo** [comment] 2020-11-12 18:58
@mtapdilli Can you try `10.4.0-beta.5`?

**Comment by jaysoo** [comment] 2020-11-12 19:26
Investigating the symlink issue. I can reproduce it in Window.s

**Comment by jaysoo** [comment] 2020-11-12 20:21
@mtapdilli Can you try `10.4.0-beta.6`?

**Comment by jaysoo** [comment] 2020-11-13 03:38
I'm able to start the bundler and run the android  app in Windows. Closing this issue.

**Closed by jaysoo** 2020-11-13 03:38 UTC

**Comment by mtapdilli** [comment] 2020-11-13 05:25
Hey @jaysoo . Just tried beta.6. I Am able to run the android app. Cheers 🥂 

**Note :** I was getting an error like `"Exception in thread "main" java.util.zip.ZipException: error in opening zip file"`. I got it to work after clearing the `".gradle\wrapper\dists\gradle-6.0.1-all\99d3u8wxs16ndehh90lbbir67"` directory. Users might get this if they already the gradle zip file in the directory. So, just a leaving a note here. 

And below one still persists : 
Running nx build-android my-app gives below error :
spawn _**path to the workspace**_\apps\my-app\android\gradlew ENOENT

I can see it has got something to do with permission. Let me know if you have any inputs on this.

**Comment by mtapdilli** [comment] 2020-12-01 08:39
@jaysoo Not sure if this is somehow causing the https://github.com/nrwl/nx-react-native/issues/23

Can we just re-open this to track the below issue that was left out ? 

- Running nx build-android my-app gives below error :
spawn _**path to the workspace**_\apps\my-app\android\gradlew ENOENT

**Comment by jaysoo** [comment] 2020-12-03 15:34
`ENOENT` is because the file is not found. I'll take to take a look on a Windows machine again, but it's  not a permissions issue.

**Comment by mtapdilli** [comment] 2020-12-04 19:01
@jaysoo I could get build-android command get to work in my system after changing[ this line](https://github.com/nrwl/nx-react-native/blob/9e1b3796b6efa844f8145a4629cd09eecca53608/packages/react-native/src/builders/build-android/build-android.impl.ts#L47)  from `join(projectRoot, 'android/gradlew')` to `join(projectRoot, 'android/gradlew.bat')`

I am thinking root cause might this : https://github.com/nodejs/node-v0.x-archive/issues/2318#issuecomment-249355505

I think we will have to update it to run gradlew/gradlew.bat based on the platform. You review it and take a call.

**Comment by jaysoo** [comment] 2020-12-04 19:15
We're doing both now:

- https://github.com/nrwl/nx-react-native/blob/main/packages/react-native/src/builders/build-android/build-android.impl.ts#L28-L29
- https://github.com/nrwl/nx-react-native/blob/main/packages/react-native/src/builders/run-android/run-android.impl.ts#L39-L40

Don't need the platform check since chmodding the unused one is fine.
